### ISSUE TITLE
Простая рандомизация добавляет несуществующий пробел

### ISSUE THREAD

**Issue by Axisar** [AiratHalitov/Ad-Generator#12]
{H|h}{ello|i|owdy}
дает
h i
H ello
h owdy
и т.д.

**Comment by AiratTop** [comment]
Спасибо! Проверю и исправлю 
UPD: У меня ошибка повторилась. Надо понять, в чем дело

**Comment by AiratTop** [comment]
В скрипте есть какая-то болезнь с появлением лишних пробелов (и слешей). 
Частично я ее исправлял тут https://github.com/AiratHalitov/ad-generator/commit/6a0d08376cb256ef4f0cb4f396e64755d9a46cc1#diff-ee084590a5f8d7b339eef53dc7524a31
Надо еще поискать, откуда изначально ноги растут.

**Comment by AiratTop** [comment]
А, всё, решил проблему. Сейчас обновлю скрипт

**Comment by AiratTop** [comment]
@Axisar 
Плагин обновлен до версии [v2.0.1 ](https://github.com/AiratHalitov/ad-generator/releases/tag/v2.0.1)
Проверьте изменения [на сайте](https://airat.biz/random/). У меня всё четко работает. 
Теперь никаких лишних пробелов не появляется. 
Плюс автоматом теперь не подчищаются пробелы до запятых и точек ([как было раньше](https://github.com/AiratHalitov/ad-generator/commit/7490f94a9e64a96334a177945962282ed75e9739#diff-ee084590a5f8d7b339eef53dc7524a31)). Как по мне - это удобнее для контроля результата. В будущем можно будет добавить это, как опцию дополнительного форматирования текста.
